# Generated by Django 5.2.17 on 2026-10-06 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název auta (např. Moje Audi)')),
                ('brand', models.CharField(max_length=50, verbose_name='Značka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Rok výroby')),
                ('license_plate', models.CharField(blank=True, max_length=15, verbose_name='SPZ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum jízdy')),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Vzdálenost (km)')),
                ('avg_consumption', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Průměrná spotřeba z PP (l/100km)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Poznámka / Trasa')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum tankování')),
                ('odometer', models.PositiveIntegerField(verbose_name='Stav tachometru (km)')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Natankováno (l)')),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Celková cena (Kč)')),
                ('calculated_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Spočítaná spotřeba (l/100km)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuelings', to='core.vehicle')),
            ],
            options={
                'ordering': ['-odometer'],
            },
        ),
    ]
